KEFIR_INTEGRATION_TESTS_SOURCES := $(wildcard \
	$(SOURCE_DIR)/tests/integration/$(INT_TEST_SUBDIR)/*.test.c)
KEFIR_INTEGRATION_TEST_SRC := $(KEFIR_INTEGRATION_TESTS_SOURCES)
KEFIR_INTEGRATION_TEST_SRC += $(SOURCE_DIR)/tests/int_test.c
KEFIR_INTEGRATION_TEST_DEPS := $(KEFIR_INTEGRATION_TEST_SRC:$(SOURCE_DIR)/%.c=$(BIN_DIR)/%.d)
KEFIR_INTEGRATION_TEST_OBJS := $(KEFIR_INTEGRATION_TEST_SRC:$(SOURCE_DIR)/%.c=$(BIN_DIR)/%.o)
KEFIR_INTEGRATION_TEST_BINS := $(KEFIR_INTEGRATION_TESTS_SOURCES:$(SOURCE_DIR)/tests/integration/%.c=$(BIN_DIR)/tests/integration/%)
KEFIR_INTEGRATION_TESTS := $(KEFIR_INTEGRATION_TESTS_SOURCES:$(SOURCE_DIR)/tests/integration/$(INT_TEST_SUBDIR)/%.test.c=integration_test_$(INT_TEST_SUBDIR)_%)
KEFIR_REBUILD_INTEGRATION_TESTS := $(KEFIR_INTEGRATION_TESTS_SOURCES:$(SOURCE_DIR)/tests/integration/$(INT_TEST_SUBDIR)/%.test.c=rebuild_integration_test_$(INT_TEST_SUBDIR)_%)

DEPS += $(KEFIR_INTEGRATION_TEST_DEPS)
OBJS += $(KEFIR_INTEGRATION_TEST_OBJS)
BINS += $(KEFIR_INTEGRATION_TEST_BINS)

$(BIN_DIR)/tests/integration/$(INT_TEST_SUBDIR)/%: INT_TEST_SUBDIR:=$(INT_TEST_SUBDIR)
$(BIN_DIR)/tests/integration/$(INT_TEST_SUBDIR)/%: $(DEPS) $(KEFIR_LIB_OBJS) \
                                                   $(BIN_DIR)/tests/int_test.o \
												   $(BIN_DIR)/tests/util/util.o \
												   $(BIN_DIR)/tests/integration/$(INT_TEST_SUBDIR)/%.o
	@mkdir -p $(@D)
	@echo "Linking $@"
	@$(CC) -o $@ $(KEFIR_LIB_OBJS) $(BIN_DIR)/tests/int_test.o \
	                             $(BIN_DIR)/tests/util/util.o \
								 $(BIN_DIR)/tests/integration/$(INT_TEST_SUBDIR)/$(@F).o

integration_test_$(INT_TEST_SUBDIR)_%: $(BIN_DIR)/tests/integration/$(INT_TEST_SUBDIR)/%.test
	@$(SOURCE_DIR)/tests/integration/run.sh $^

rebuild_integration_test_$(INT_TEST_SUBDIR)_%: INT_TEST_SUBDIR:=$(INT_TEST_SUBDIR)
rebuild_integration_test_$(INT_TEST_SUBDIR)_%: $(BIN_DIR)/tests/integration/$(INT_TEST_SUBDIR)/%.test
	@echo "Rebuilding $(SOURCE_DIR)/tests/integration/$(INT_TEST_SUBDIR)/$(<F).result"
	$^ > $(SOURCE_DIR)/tests/integration/$(INT_TEST_SUBDIR)/$(<F).result

integration_tests: $(KEFIR_INTEGRATION_TESTS)

rebuild_integration_tests: $(KEFIR_REBUILD_INTEGRATION_TESTS)

test: integration_tests

.PHONY: integration_tests rebuild_integration_tests