#ifndef KEFIR_IR_OPCODES_H_
#define KEFIR_IR_OPCODES_H_

#include "kefir/core/base.h"

typedef enum kefir_iropcode {
    KEFIR_IROPCODE_RESERVED = 0x00,
    // Flow control
    KEFIR_IROPCODE_NOP,
    KEFIR_IROPCODE_JMP,
    KEFIR_IROPCODE_BRANCH,
    KEFIR_IROPCODE_RET,

    // Stack control
    KEFIR_IROPCODE_PUSH,
    KEFIR_IROPCODE_POP,
    KEFIR_IROPCODE_PICK,
    KEFIR_IROPCODE_DROP,

    // Integer arithmetics
    KEFIR_IROPCODE_IADD,
    KEFIR_IROPCODE_IADD1,
    KEFIR_IROPCODE_ISUB,
    KEFIR_IROPCODE_IMUL,
    KEFIR_IROPCODE_IDIV,
    KEFIR_IROPCODE_IMOD,
    KEFIR_IROPCODE_INEG,
    
    // Bitwise
    KEFIR_IROPCODE_INOT,
    KEFIR_IROPCODE_IAND,
    KEFIR_IROPCODE_IOR,
    KEFIR_IROPCODE_IXOR,
    KEFIR_IROPCODE_ILSHIFT,
    KEFIR_IROPCODE_IRSHIFT,

    // Conditions
    KEFIR_IROPCODE_COMPARE,
    KEFIR_IROPCODE_BAND,
    KEFIR_IROPCODE_BOR,
    KEFIR_IROPCODE_BNOT,

    // Types
    KEFIR_IROPCODE_ASBOOL,
    KEFIR_IROPCODE_TRUNCATE
} kefir_iropcode_t;

#endif