image: freebsd/13.x
packages:
  - gmake
  - llvm
  - binutils
  - valgrind
  - libxslt
sources:
  - https://git.sr.ht/~jprotopopov/kefir
tasks:
  - test: |
      cd kefir
      gmake test PLATFORM=freebsd MEMCHECK=yes OPT=-O3 SANITIZE=undefined CC=clang
  - build: |
      cd kefir
      gmake clean
      gmake all PLATFORM=freebsd OPT=-O3 CC=clang
triggers:
  - action: email
    condition: failure
    to: jprotopopov1122@gmail.com
