image: ubuntu/focal
packages:
  - build-essential
  - gcc-10
  - clang-format
  - valgrind
  - xsltproc
  - musl-dev
  - musl-tools
  - wget
sources:
  - https://git.sr.ht/~jprotopopov/kefir
  - https://github.com/protopopov1122/c-testsuite.git
tasks:
  - kefircc: |
      cd kefir
      make ./bin/kefir OPT=-O2 -j$(nproc)
  - lua_tests: |
      cd kefir
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/bin/libs
      export LC_ALL=C.UTF-8
      ./source/tests/misc/run-lua-tests.sh "$(pwd)/bin/kefir -I /usr/include/x86_64-linux-musl" "$(pwd)/source/runtime/amd64_sysv.s" "$(pwd)/bin/lua-test"
  - c_testsuite: |
      as -o rt.o kefir/source/runtime/amd64_sysv.s
      cd c-testsuite
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/kefir/bin/libs
      export KEFIRCC="$HOME/kefir/bin/kefir"
      export KEFIRRT="$HOME/rt.o /usr/lib/x86_64-linux-musl/crt1.o /usr/lib/x86_64-linux-musl/libc.a"
      export CFLAGS="-I /usr/include/x86_64-linux-musl --feature-non-strict-qualifiers"
      export LC_ALL=C.UTF-8 
      ./single-exec kefircc | tee ~/c-tests.log
      [[ "x$(cat ~/c-tests.log | scripts/tapsummary | grep 'fail 0' | wc -l)" == "x1" ]] || exit 1
  - gcc_torture: |
      wget ftp://ftp.gnu.org/gnu/gcc/gcc-11.2.0/gcc-11.2.0.tar.xz
      tar xvf gcc-11.2.0.tar.xz
      export TORTURE=$PWD/gcc-11.2.0/gcc/testsuite/gcc.c-torture
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/kefir/bin/libs
      export KEFIRCC="$HOME/kefir/bin/kefir -I /usr/include/x86_64-linux-musl"
      export LIBC="/usr/lib/x86_64-linux-musl/crt1.o /usr/lib/x86_64-linux-musl/libc.a" 
      ./kefir/source/tests/misc/run_gcc_torture_suite.sh 2>&1 | tee torture.log
      grep -i "fatal\|abort\|timeout\|segm" torture.log && exit 1 || true
triggers:
  - action: email
    condition: failure
    to: jprotopopov1122@gmail.com
