image: ubuntu/focal
packages:
  - build-essential
  - gcc-10
  - clang-format
  - valgrind
  - xsltproc
sources:
  - https://git.sr.ht/~jprotopopov/kefir
tasks:
  - test: |
      cd kefir
      LC_ALL=C.UTF-8 make test MEMCHECK=yes OPT=-O3 SANITIZE=undefined CC=gcc-10 -j$(nproc)
  - build: |
      cd kefir
      make clean
      make all OPT=-O3 CC=gcc-10
triggers:
  - action: email
    condition: failure
    to: jprotopopov1122@gmail.com
