#ifndef KEFIR_CODEGEN_AMD64_LABELS_H_
#define KEFIR_CODEGEN_AMD64_LABELS_H_

#include "kefir/core/base.h"

#define KEFIR_AMD64_SYSV_PROCEDURE_LABEL "%s"
#define KEFIR_AMD64_SYSV_PROCEDURE_BODY_LABEL "__%s_body"
#define KEFIR_AMD64_SYSV_PROCEDURE_EPILOGUE_LABEL "__%s_epilogue"
#define KEFIR_AMD64_SYSV_FUNCTION_GATE_LABEL "__%s_gate"

#endif