#include "kefir/codegen/amd64/system-v/runtime.h"

const char *KEFIR_AMD64_SYSTEM_V_RUNTIME_SYMBOLS[] = {
    KEFIR_AMD64_SYSTEM_V_RUNTIME_PRESERVE_STATE, KEFIR_AMD64_SYSTEM_V_RUNTIME_RESTORE_STATE,
    KEFIR_AMD64_SYSTEM_V_RUNTIME_SAVE_REGISTERS, KEFIR_AMD64_SYSTEM_V_RUNTIME_VARARG_INT,
    KEFIR_AMD64_SYSTEM_V_RUNTIME_VARARG_SSE,     KEFIR_AMD64_SYSTEM_V_RUNTIME_VARARG_COPY};

kefir_size_t KEFIR_AMD64_SYSTEM_V_RUNTIME_SYMBOL_COUNT =
    sizeof(KEFIR_AMD64_SYSTEM_V_RUNTIME_SYMBOLS) / sizeof(KEFIR_AMD64_SYSTEM_V_RUNTIME_SYMBOLS[0]);
