<?xml version="1.0"?>
<xsl:stylesheet version="1.1"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="text" encoding="utf-8" media-type="text/plain" />
    <xsl:variable name="lcletters">abcdefghijklmnopqrstuvwxyz</xsl:variable>
    <xsl:variable name="ucletters">ABCDEFGHIJKLMNOPQRSTUVWXYZ</xsl:variable>
	<xsl:template match="opcodes">
		<xsl:text>#ifndef KEFIR_IR_MNEMONIC_H_
#define KEFIR_IR_MNEMONIC_H_

#include "kefir/ir/opcodes.h"

// Do not edit this file. It is autogenerated. Edit resources/opcodes.xml instead.
</xsl:text>
		<xsl:for-each select="opcode">
			<xsl:text>#define KEFIR_IROPCODE_MNEMONIC_</xsl:text>
			<xsl:value-of select="translate(@id, $lcletters, $ucletters)" />
			<xsl:text> "</xsl:text>
			<xsl:value-of select="@mnemonic" />
			<xsl:text>"&#xa;</xsl:text>
		</xsl:for-each>
		<xsl:text>
const char *kefir_iropcode_mnemonic(kefir_iropcode_t);

#endif&#xa;</xsl:text>
	</xsl:template>

</xsl:stylesheet>