#include "kefir/codegen/amd64/opcodes.h"
#include "kefir/core/util.h"
#include "kefir/ir/symbolic.h"

#define LABEL(opcode) "__kefirrt_" opcode "_impl"

static struct {
    kefir_iropcode_t opcode;
    const char *handler;
} OPCODE_HANDLERS[] = {
    { KEFIR_IROPCODE_NOP,        LABEL(KEFIR_IROPCODE_SYMBOL_NOP) },
    { KEFIR_IROPCODE_JMP,        LABEL(KEFIR_IROPCODE_SYMBOL_JMP) },
    { KEFIR_IROPCODE_BRANCH,     LABEL(KEFIR_IROPCODE_SYMBOL_BRANCH) },
    { KEFIR_IROPCODE_PUSHI64,    LABEL(KEFIR_IROPCODE_SYMBOL_PUSHI64) },
    { KEFIR_IROPCODE_POP,        LABEL(KEFIR_IROPCODE_SYMBOL_POP) },
    { KEFIR_IROPCODE_PICK,       LABEL(KEFIR_IROPCODE_SYMBOL_PICK) },
    { KEFIR_IROPCODE_PUT,        LABEL(KEFIR_IROPCODE_SYMBOL_PUT) },
    { KEFIR_IROPCODE_INSERT,     LABEL(KEFIR_IROPCODE_SYMBOL_INSERT) },
    { KEFIR_IROPCODE_XCHG,       LABEL(KEFIR_IROPCODE_SYMBOL_XCHG) },
    { KEFIR_IROPCODE_DROP,       LABEL(KEFIR_IROPCODE_SYMBOL_DROP) },
    { KEFIR_IROPCODE_IADD,       LABEL(KEFIR_IROPCODE_SYMBOL_IADD) },
    { KEFIR_IROPCODE_IADD1,      LABEL(KEFIR_IROPCODE_SYMBOL_IADD1) },
    { KEFIR_IROPCODE_ISUB,       LABEL(KEFIR_IROPCODE_SYMBOL_ISUB) },
    { KEFIR_IROPCODE_IMUL,       LABEL(KEFIR_IROPCODE_SYMBOL_IMUL) },
    { KEFIR_IROPCODE_IDIV,       LABEL(KEFIR_IROPCODE_SYMBOL_IDIV) },
    { KEFIR_IROPCODE_IMOD,       LABEL(KEFIR_IROPCODE_SYMBOL_IMOD) },
    { KEFIR_IROPCODE_INEG,       LABEL(KEFIR_IROPCODE_SYMBOL_INEG) },
    { KEFIR_IROPCODE_INOT,       LABEL(KEFIR_IROPCODE_SYMBOL_INOT) },
    { KEFIR_IROPCODE_IAND,       LABEL(KEFIR_IROPCODE_SYMBOL_IAND) },
    { KEFIR_IROPCODE_IOR,        LABEL(KEFIR_IROPCODE_SYMBOL_IOR) },
    { KEFIR_IROPCODE_IXOR,       LABEL(KEFIR_IROPCODE_SYMBOL_IXOR) },
    { KEFIR_IROPCODE_IRSHIFT,    LABEL(KEFIR_IROPCODE_SYMBOL_IRSHIFT) },
    { KEFIR_IROPCODE_IARSHIFT,   LABEL(KEFIR_IROPCODE_SYMBOL_IARSHIFT) },
    { KEFIR_IROPCODE_ILSHIFT,    LABEL(KEFIR_IROPCODE_SYMBOL_ILSHIFT) },
    { KEFIR_IROPCODE_IEQUALS,    LABEL(KEFIR_IROPCODE_SYMBOL_IEQUALS) },
    { KEFIR_IROPCODE_IGREATER,   LABEL(KEFIR_IROPCODE_SYMBOL_IGREATER) },
    { KEFIR_IROPCODE_ILESSER,    LABEL(KEFIR_IROPCODE_SYMBOL_ILESSER) },
    { KEFIR_IROPCODE_IABOVE,     LABEL(KEFIR_IROPCODE_SYMBOL_IABOVE) },
    { KEFIR_IROPCODE_IBELOW,     LABEL(KEFIR_IROPCODE_SYMBOL_IBELOW) },
    { KEFIR_IROPCODE_BAND,       LABEL(KEFIR_IROPCODE_SYMBOL_BAND) },
    { KEFIR_IROPCODE_BOR,        LABEL(KEFIR_IROPCODE_SYMBOL_BOR) },
    { KEFIR_IROPCODE_BNOT,       LABEL(KEFIR_IROPCODE_SYMBOL_BNOT) },
    { KEFIR_IROPCODE_TRUNCATE1,  LABEL(KEFIR_IROPCODE_SYMBOL_TRUNCATE1) },
    { KEFIR_IROPCODE_EXTEND8,    LABEL(KEFIR_IROPCODE_SYMBOL_EXTEND8) },
    { KEFIR_IROPCODE_EXTEND16,   LABEL(KEFIR_IROPCODE_SYMBOL_EXTEND16) },
    { KEFIR_IROPCODE_EXTEND32,   LABEL(KEFIR_IROPCODE_SYMBOL_EXTEND32) },
    { KEFIR_IROPCODE_OFFSETPTR,  LABEL(KEFIR_IROPCODE_SYMBOL_OFFSETPTR) },
    { KEFIR_IROPCODE_ELEMENTPTR, LABEL(KEFIR_IROPCODE_SYMBOL_ELEMENTPTR) },
    { KEFIR_IROPCODE_LOAD8U,     LABEL(KEFIR_IROPCODE_SYMBOL_LOAD8U) },
    { KEFIR_IROPCODE_LOAD8I,     LABEL(KEFIR_IROPCODE_SYMBOL_LOAD8I) },
    { KEFIR_IROPCODE_LOAD16U,    LABEL(KEFIR_IROPCODE_SYMBOL_LOAD16U) },
    { KEFIR_IROPCODE_LOAD16I,    LABEL(KEFIR_IROPCODE_SYMBOL_LOAD16I) },
    { KEFIR_IROPCODE_LOAD32U,    LABEL(KEFIR_IROPCODE_SYMBOL_LOAD32U) },
    { KEFIR_IROPCODE_LOAD32I,    LABEL(KEFIR_IROPCODE_SYMBOL_LOAD32I) },
    { KEFIR_IROPCODE_LOAD64,     LABEL(KEFIR_IROPCODE_SYMBOL_LOAD64) },
    { KEFIR_IROPCODE_STORE8,     LABEL(KEFIR_IROPCODE_SYMBOL_STORE8) },
    { KEFIR_IROPCODE_STORE16,    LABEL(KEFIR_IROPCODE_SYMBOL_STORE16) },
    { KEFIR_IROPCODE_STORE32,    LABEL(KEFIR_IROPCODE_SYMBOL_STORE32) },
    { KEFIR_IROPCODE_STORE64,    LABEL(KEFIR_IROPCODE_SYMBOL_STORE64) },
    { KEFIR_IROPCODE_GETLOCALS,  LABEL(KEFIR_IROPCODE_SYMBOL_GETLOCALS) },
    { KEFIR_IROPCODE_F32ADD,     LABEL(KEFIR_IROPCODE_SYMBOL_F32ADD) },
    { KEFIR_IROPCODE_F32SUB,     LABEL(KEFIR_IROPCODE_SYMBOL_F32SUB) },
    { KEFIR_IROPCODE_F32MUL,     LABEL(KEFIR_IROPCODE_SYMBOL_F32MUL) },
    { KEFIR_IROPCODE_F32DIV,     LABEL(KEFIR_IROPCODE_SYMBOL_F32DIV) },
    { KEFIR_IROPCODE_F64ADD,     LABEL(KEFIR_IROPCODE_SYMBOL_F64ADD) },
    { KEFIR_IROPCODE_F64SUB,     LABEL(KEFIR_IROPCODE_SYMBOL_F64SUB) },
    { KEFIR_IROPCODE_F64MUL,     LABEL(KEFIR_IROPCODE_SYMBOL_F64MUL) },
    { KEFIR_IROPCODE_F64DIV,     LABEL(KEFIR_IROPCODE_SYMBOL_F64DIV) },
    { KEFIR_IROPCODE_F32EQUALS,  LABEL(KEFIR_IROPCODE_SYMBOL_F32EQUALS) },
    { KEFIR_IROPCODE_F32GREATER, LABEL(KEFIR_IROPCODE_SYMBOL_F32GREATER) },
    { KEFIR_IROPCODE_F32LESSER,  LABEL(KEFIR_IROPCODE_SYMBOL_F32LESSER) },
    { KEFIR_IROPCODE_F64EQUALS,  LABEL(KEFIR_IROPCODE_SYMBOL_F64EQUALS) },
    { KEFIR_IROPCODE_F64GREATER, LABEL(KEFIR_IROPCODE_SYMBOL_F64GREATER) },
    { KEFIR_IROPCODE_F64LESSER,  LABEL(KEFIR_IROPCODE_SYMBOL_F64LESSER) },
    { KEFIR_IROPCODE_F32CINT,    LABEL(KEFIR_IROPCODE_SYMBOL_F32CINT) },
    { KEFIR_IROPCODE_F64CINT,    LABEL(KEFIR_IROPCODE_SYMBOL_F64CINT) },
    { KEFIR_IROPCODE_INTCF32,    LABEL(KEFIR_IROPCODE_SYMBOL_INTCF32) },
    { KEFIR_IROPCODE_INTCF64,    LABEL(KEFIR_IROPCODE_SYMBOL_INTCF64) },
    { KEFIR_IROPCODE_F32CF64,    LABEL(KEFIR_IROPCODE_SYMBOL_F32CF64) },
    { KEFIR_IROPCODE_F64CF32,    LABEL(KEFIR_IROPCODE_SYMBOL_F64CF32) }
};

const char *kefir_amd64_iropcode_handler(kefir_iropcode_t opcode) {
    for (kefir_size_t i = 0; i < sizeof(OPCODE_HANDLERS) / sizeof(OPCODE_HANDLERS[0]); i++) {
        if (OPCODE_HANDLERS[i].opcode == opcode) {
            return OPCODE_HANDLERS[i].handler;
        }
    }
    return NULL;
}

kefir_result_t kefir_amd64_iropcode_handler_list(kefir_result_t (*callback)(kefir_iropcode_t, const char *, void *), void *payload) {
    for (kefir_size_t i = 0; i < sizeof(OPCODE_HANDLERS) / sizeof(OPCODE_HANDLERS[0]); i++) {
        REQUIRE_OK(callback(OPCODE_HANDLERS[i].opcode, OPCODE_HANDLERS[i].handler, payload));
    }
    return KEFIR_OK;
}