#ifndef KEFIR_AST_BASE_H_
#define KEFIR_AST_BASE_H_

#include "kefir/core/basic-types.h"

// Forward declarations
typedef struct kefir_ast_type kefir_ast_type_t;
typedef struct kefir_ast_type_traits kefir_ast_type_traits_t;
typedef struct kefir_ast_node_base kefir_ast_node_base_t;
typedef struct kefir_ast_scoped_identifier kefir_ast_scoped_identifier_t;
typedef struct kefir_ast_context kefir_ast_context_t;
typedef struct kefir_ast_type_bundle kefir_ast_type_bundle_t;
typedef struct kefir_ast_constant_expression kefir_ast_constant_expression_t;
typedef struct kefir_ast_alignment kefir_ast_alignment_t;
typedef struct kefir_ast_global_context kefir_ast_global_context_t;
typedef struct kefir_ast_local_context kefir_ast_local_context_t;
typedef struct kefir_ast_function_declaration_context kefir_ast_function_declaration_context_t;

#endif
