#ifndef KEFIR_AST_TYPE_H_
#define KEFIR_AST_TYPE_H_

#include "kefir/core/basic-types.h"

typedef enum kefir_ast_type_tag {
    KEFIR_AST_TYPE_BOOL_SCALAR,
    KEFIR_AST_TYPE_UINT8_SCALAR,
    KEFIR_AST_TYPE_UINT16_SCALAR,
    KEFIR_AST_TYPE_UINT32_SCALAR,
    KEFIR_AST_TYPE_UINT64_SCALAR,
    KEFIR_AST_TYPE_INT8_SCALAR,
    KEFIR_AST_TYPE_INT16_SCALAR,
    KEFIR_AST_TYPE_INT32_SCALAR,
    KEFIR_AST_TYPE_INT64_SCALAR,
    KEFIR_AST_TYPE_FLOAT32_SCALAR,
    KEFIR_AST_TYPE_FLOAT64_SCALAR
} kefir_ast_type_tag_t;

#endif