#include <stdio.h>
#include "kefir/core/util.h"
#include "kefir/test/unit_test.h"
#include <assert.h>

DECLARE_CASE(amd64_sysv_abi_data_test1);
DECLARE_CASE(amd64_sysv_abi_data_test2);
DECLARE_CASE(amd64_sysv_abi_data_test3);
DECLARE_CASE(amd64_sysv_abi_data_test4);
DECLARE_CASE(amd64_sysv_abi_data_test5);
DECLARE_CASE(amd64_sysv_abi_data_test6);
DECLARE_CASE(amd64_sysv_abi_data_test7);
DECLARE_CASE(amd64_sysv_abi_data_test8);
DECLARE_CASE(amd64_sysv_abi_data_test9);
DECLARE_CASE(amd64_sysv_abi_classification_test1);
DECLARE_CASE(amd64_sysv_abi_classification_test2);
DECLARE_CASE(amd64_sysv_abi_classification_test3);
DECLARE_CASE(amd64_sysv_abi_classification_test4);
DECLARE_CASE(amd64_sysv_abi_classification_test5);
DECLARE_CASE(amd64_sysv_abi_classification_test6);
DECLARE_CASE(amd64_sysv_abi_classification_test7);
DECLARE_CASE(amd64_sysv_abi_classification_test8);
DECLARE_CASE(amd64_sysv_abi_classification_test9);
DECLARE_CASE(amd64_sysv_abi_classification_test10);
DECLARE_CASE(amd64_sysv_abi_classification_test11);
DECLARE_CASE(amd64_sysv_abi_classification_test12);
DECLARE_CASE(amd64_sysv_abi_classification_test13);
DECLARE_CASE(amd64_sysv_abi_classification_test14);
DECLARE_CASE(amd64_sysv_abi_classification_test15);
DECLARE_CASE(amd64_sysv_abi_allocation_test1);
DECLARE_CASE(amd64_sysv_abi_allocation_test2);
DECLARE_CASE(amd64_sysv_abi_allocation_test3);
DECLARE_CASE(amd64_sysv_abi_allocation_test4);
DECLARE_CASE(amd64_sysv_abi_allocation_test5);
DECLARE_CASE(amd64_sysv_abi_allocation_test6);

DECLARE_CASE(ast_type_analysis_integer_promotion1);
DECLARE_CASE(ast_type_analysis_arithmetic_conversion1);
DECLARE_CASE(ast_type_analysis_arithmetic_conversion2);
DECLARE_CASE(ast_type_analysis_arithmetic_conversion3);
DECLARE_CASE(ast_ordinary_scope_objects1);
DECLARE_CASE(ast_ordinary_scope_objects2);
DECLARE_CASE(ast_ordinary_scope_objects3);
DECLARE_CASE(ast_ordinary_scope_objects4);
DECLARE_CASE(ast_ordinary_scope_objects5);
DECLARE_CASE(ast_ordinary_scope_objects6);
DECLARE_CASE(ast_ordinary_scope_objects7);
DECLARE_CASE(ast_ordinary_scope_objects8);
DECLARE_CASE(ast_ordinary_scope_objects9);
DECLARE_CASE(ast_ordinary_scope_objects10);
DECLARE_CASE(ast_ordinary_scope_objects11);
DECLARE_CASE(ast_ordinary_scope_objects12);
DECLARE_CASE(ast_ordinary_scope_objects13);
DECLARE_CASE(ast_ordinary_scope_objects14);
DECLARE_CASE(ast_ordinary_scope_objects15);
DECLARE_CASE(ast_type_construction1);
DECLARE_CASE(ast_type_construction2);
DECLARE_CASE(ast_type_construction3);
DECLARE_CASE(ast_type_construction4);
DECLARE_CASE(ast_type_construction5);
DECLARE_CASE(ast_type_construction6);
DECLARE_CASE(ast_type_construction7);
DECLARE_CASE(ast_type_construction8);
DECLARE_CASE(ast_nodes_constants);
DECLARE_CASE(ast_nodes_identifiers);
DECLARE_CASE(ast_nodes_string_literals);
DECLARE_CASE(ast_nodes_type_name);
DECLARE_CASE(ast_nodes_array_subscripts);
DECLARE_CASE(ast_nodes_function_calls);
DECLARE_CASE(ast_nodes_struct_members);
DECLARE_CASE(ast_nodes_unary_operations);
DECLARE_CASE(ast_nodes_binary_operations);
DECLARE_CASE(ast_nodes_generic_selections);
DECLARE_CASE(ast_type_compatibility1);
DECLARE_CASE(ast_type_basic_compatibility);
DECLARE_CASE(ast_type_enum_compatibility);
DECLARE_CASE(ast_type_pointer_compatibility);
DECLARE_CASE(ast_type_qualified_compatibility);
DECLARE_CASE(ast_type_struct_compatibility);
DECLARE_CASE(ast_type_union_compatibility);
DECLARE_CASE(ast_type_array_compatibility);
DECLARE_CASE(ast_type_function_compatibility);
DECLARE_CASE(ast_type_basic_composite);
DECLARE_CASE(ast_type_pointer_composite);
DECLARE_CASE(ast_type_enum_composite);
DECLARE_CASE(ast_type_qualified_composite);
DECLARE_CASE(ast_type_struct_composite);
DECLARE_CASE(ast_type_union_composite);
DECLARE_CASE(ast_type_array_composite);
DECLARE_CASE(ast_type_function_composite);
DECLARE_CASE(ast_type_scope1);
DECLARE_CASE(ast_type_scope2);
DECLARE_CASE(ast_type_scope3);
DECLARE_CASE(ast_ordinary_constant_scope1);
DECLARE_CASE(ast_ordinary_typedef_scope1);
DECLARE_CASE(ast_ordinary_scope_composite_objects_external);
DECLARE_CASE(ast_ordinary_scope_composite_objects_external_declaration);
DECLARE_CASE(ast_ordinary_scope_composite_objects_thread_local_external);
DECLARE_CASE(ast_ordinary_scope_composite_objects_thread_local_external_declaration);
DECLARE_CASE(ast_ordinary_scope_composite_objects_static);
DECLARE_CASE(ast_ordinary_scope_composite_objects_static_thread_local);
DECLARE_CASE(ast_ordinary_scope_composite_objects_local_external);
DECLARE_CASE(ast_ordinary_scope_composite_objects_local_thread_local_external);
DECLARE_CASE(ast_ordinary_function_scope1);
DECLARE_CASE(ast_ordinary_function_scope2);
DECLARE_CASE(ast_ordinary_function_scope3);
DECLARE_CASE(ast_ordinary_function_scope4);
DECLARE_CASE(ast_ordinary_function_scope5);
DECLARE_CASE(ast_node_analysis_constants);
DECLARE_CASE(ast_node_analysis_string_literals);
DECLARE_CASE(ast_node_analysis_identifiers);
DECLARE_CASE(ast_node_analysis_array_subscripts);
DECLARE_CASE(ast_node_analysis_struct_members);
DECLARE_CASE(ast_node_analysis_function_calls);
DECLARE_CASE(ast_node_analysis_unary_operation_arithmetic);
DECLARE_CASE(ast_node_analysis_unary_operation_address);
DECLARE_CASE(ast_node_analysis_unary_operation_indirect);
DECLARE_CASE(ast_node_analysis_unary_operation_incdec);
DECLARE_CASE(ast_node_analysis_type_name);
DECLARE_CASE(ast_node_analysis_generic_selections);

TEST_SUITE(mainSuite,
    &amd64_sysv_abi_data_test1,
    &amd64_sysv_abi_data_test2,
    &amd64_sysv_abi_data_test3,
    &amd64_sysv_abi_data_test4,
    &amd64_sysv_abi_data_test5,
    &amd64_sysv_abi_data_test6,
    &amd64_sysv_abi_data_test7,
    &amd64_sysv_abi_data_test8,
    &amd64_sysv_abi_data_test9,
    &amd64_sysv_abi_classification_test1,
    &amd64_sysv_abi_classification_test2,
    &amd64_sysv_abi_classification_test3,
    &amd64_sysv_abi_classification_test4,
    &amd64_sysv_abi_classification_test5,
    &amd64_sysv_abi_classification_test6,
    &amd64_sysv_abi_classification_test7,
    &amd64_sysv_abi_classification_test8,
    &amd64_sysv_abi_classification_test9,
    &amd64_sysv_abi_classification_test10,
    &amd64_sysv_abi_classification_test11,
    &amd64_sysv_abi_classification_test12,
    &amd64_sysv_abi_classification_test13,
    &amd64_sysv_abi_classification_test14,
    &amd64_sysv_abi_classification_test15,
    &amd64_sysv_abi_allocation_test1,
    &amd64_sysv_abi_allocation_test2,
    &amd64_sysv_abi_allocation_test3,
    &amd64_sysv_abi_allocation_test4,
    &amd64_sysv_abi_allocation_test5,
    &amd64_sysv_abi_allocation_test6,
    &ast_type_analysis_integer_promotion1,
    &ast_type_analysis_arithmetic_conversion1,
    &ast_type_analysis_arithmetic_conversion2,
    &ast_type_analysis_arithmetic_conversion3,
    &ast_ordinary_scope_objects1,
    &ast_ordinary_scope_objects2,
    &ast_ordinary_scope_objects3,
    &ast_ordinary_scope_objects4,
    &ast_ordinary_scope_objects5,
    &ast_ordinary_scope_objects6,
    &ast_ordinary_scope_objects7,
    &ast_ordinary_scope_objects8,
    &ast_ordinary_scope_objects9,
    &ast_ordinary_scope_objects10,
    &ast_ordinary_scope_objects11,
    &ast_ordinary_scope_objects12,
    &ast_ordinary_scope_objects13,
    &ast_ordinary_scope_objects14,
    &ast_ordinary_scope_objects15,
    &ast_type_construction1,
    &ast_type_construction2,
    &ast_type_construction3,
    &ast_type_construction4,
    &ast_type_construction5,
    &ast_type_construction6,
    &ast_type_construction7,
    &ast_type_construction8,
    &ast_nodes_constants,
    &ast_nodes_identifiers,
    &ast_nodes_string_literals,
    &ast_nodes_type_name,
    &ast_nodes_array_subscripts,
    &ast_nodes_function_calls,
    &ast_nodes_struct_members,
    &ast_nodes_unary_operations,
    &ast_nodes_binary_operations,
    &ast_nodes_generic_selections,
    &ast_type_compatibility1,
    &ast_type_basic_compatibility,
    &ast_type_enum_compatibility,
    &ast_type_pointer_compatibility,
    &ast_type_qualified_compatibility,
    &ast_type_struct_compatibility,
    &ast_type_union_compatibility,
    &ast_type_array_compatibility,
    &ast_type_function_compatibility,
    &ast_type_basic_composite,
    &ast_type_pointer_composite,
    &ast_type_enum_composite,
    &ast_type_qualified_composite,
    &ast_type_struct_composite,
    &ast_type_union_composite,
    &ast_type_array_composite,
    &ast_type_function_composite,
    &ast_type_scope1,
    &ast_type_scope2,
    &ast_type_scope3,
    &ast_ordinary_constant_scope1,
    &ast_ordinary_typedef_scope1,
    &ast_ordinary_scope_composite_objects_external,
    &ast_ordinary_scope_composite_objects_external_declaration,
    &ast_ordinary_scope_composite_objects_thread_local_external,
    &ast_ordinary_scope_composite_objects_thread_local_external_declaration,
    &ast_ordinary_scope_composite_objects_static,
    &ast_ordinary_scope_composite_objects_static_thread_local,
    &ast_ordinary_scope_composite_objects_local_external,
    &ast_ordinary_scope_composite_objects_local_thread_local_external,
    &ast_ordinary_function_scope1,
    &ast_ordinary_function_scope2,
    &ast_ordinary_function_scope3,
    &ast_ordinary_function_scope4,
    &ast_ordinary_function_scope5,
    &ast_node_analysis_constants,
    &ast_node_analysis_string_literals,
    &ast_node_analysis_identifiers,
    &ast_node_analysis_array_subscripts,
    &ast_node_analysis_struct_members,
    &ast_node_analysis_function_calls,
    &ast_node_analysis_unary_operation_arithmetic,
    &ast_node_analysis_unary_operation_address,
    &ast_node_analysis_unary_operation_indirect,
    &ast_node_analysis_unary_operation_incdec,
    &ast_node_analysis_type_name,
    &ast_node_analysis_generic_selections
);

int main(int argc, const char **argv) {
    UNUSED(argc);
    UNUSED(argv);
    return kft_run_test_suite(mainSuite, mainSuiteLength, NULL);
}